apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    app.kubernetes.io/name: cadence-md
    app.kubernetes.io/component: flower
spec:
  ports:
    - name: http
      port: 5555
      targetPort: http
  selector:
    app.kubernetes.io/name: cadence-md
    app.kubernetes.io/component: flower
