apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/name: cadence-md
    app.kubernetes.io/component: qdrant
spec:
  ports:
    - name: http
      port: 6333
      targetPort: http
    - name: grpc
      port: 6334
      targetPort: grpc
  selector:
    app.kubernetes.io/name: cadence-md
    app.kubernetes.io/component: qdrant
