FROM python:3.13-slim
WORKDIR /cadence_md
RUN apt-get update -y && apt-get install python3-pip curl -y \
    && rm -rf /var/lib/apt/lists/*
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
#CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
