apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache
  labels:
    app.kubernetes.io/name: cadence-md
    app.kubernetes.io/component: vllm-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
